name: CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      OLLAMA_MODEL_NAME: "phi4-mini"
      OLLAMA_VERSION: "0.11.7"
      FFMPEG_VERSION: "release"
      PYTHON_VERSION: "3.12"
      POETRY_VERSION: "2.1.3"
      DAPR_CLI_VERSION: "1.15.1"
      DAPR_RUNTIME_VERSION: "1.15.10"
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main
      with:
        # this might remove tools that are actually needed,
        # if set to "true" but frees about 6 GB
        tool-cache: false
        
        # all of these default to true, but feel free to set to
        # "false" if necessary for your workflow
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: true

    - name: Additional cleanup
      run: |
        echo "=== Additional disk cleanup ==="
        # Clean package managers
        sudo apt-get clean
        sudo apt-get autoremove -y
        sudo apt-get autoclean
        
        # Clean Docker completely
        docker system prune -a -f --volumes
        
        echo "=== Final disk usage ==="
        df -h

    - name: Setup FFmpeg
      uses: FedericoCarboni/setup-ffmpeg@v3
      id: setup-ffmpeg
      with:
        ffmpeg-version: ${{ env.FFMPEG_VERSION }}
    
    - name: Setup Dapr CLI specific version
      uses: dapr/setup-dapr@v1
      with:
        version: ${{ env.DAPR_CLI_VERSION }}
      id: install

    - name: Initialize Dapr
      id: dapr-setup
      continue-on-error: true
      run: |
        export GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
        dapr init --runtime-version=${{ env.DAPR_RUNTIME_VERSION }}
        dapr --version
        # Verify daprd exists in the expected location
        ls -la $HOME/.dapr/bin/
        # Add Dapr CLI to PATH for current session and make it persistent
        echo "$HOME/.dapr/bin" >> $GITHUB_PATH
        export PATH="$HOME/.dapr/bin:$PATH"
        # Verify daprd is accessible
        if command -v daprd &> /dev/null; then
          echo "daprd found in PATH: $(which daprd)"
          daprd --version
          echo "dapr-available=true" >> $GITHUB_OUTPUT
        else
          echo "daprd not found in PATH, checking direct path..."
          if [ -f "$HOME/.dapr/bin/daprd" ]; then
            echo "daprd found at: $HOME/.dapr/bin/daprd"
            $HOME/.dapr/bin/daprd --version
            echo "dapr-available=true" >> $GITHUB_OUTPUT
          else
            echo "ERROR: daprd not found"
            echo "dapr-available=false" >> $GITHUB_OUTPUT
            exit 1
          fi
        fi
        # Create symlink for compatibility with test configuration  
        sudo mkdir -p /home/vscode/.dapr/bin
        sudo ln -sf $HOME/.dapr/bin/daprd /home/vscode/.dapr/bin/daprd
    
    - name: Install Ollama
      uses: ai-action/setup-ollama@v1
      with:
        version: ${{ env.OLLAMA_VERSION }}

    - name: Setup Ollama Chat completion model
      run: |
        echo "Starting Ollama service..."
        ollama serve &
        
        # Wait for Ollama to be ready
        echo "Waiting for Ollama to start..."
        timeout 60 bash -c 'until curl -s http://localhost:11434/api/tags > /dev/null 2>&1; do sleep 2; done'
        
        echo "Pulling ${{ env.OLLAMA_MODEL_NAME }} model..."
        ollama pull ${{ env.OLLAMA_MODEL_NAME }}

    - name: Ensure Azure CLI is installed
      run: |
        if ! command -v az &> /dev/null; then
          echo "Azure CLI not found. Installing..."
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
        else
          echo "Azure CLI is already installed"
        fi

    - name: Azure login (service principal)
      if: ${{ env.AZURE_CREDENTIALS != '' && contains(env.AZURE_CREDENTIALS, 'clientId') }}
      uses: azure/login@v2
      with:
        creds: ${{ env.AZURE_CREDENTIALS }}

    - name: Set up Python
      id: setup-python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: ${{ env.POETRY_VERSION }}
        virtualenvs-create: true
        virtualenvs-in-project: true
        virtualenvs-path: .venv
        installer-parallel: true

    - name: Load cached venv
      id: cached-poetry-dependencies
      uses: actions/cache@v4
      with:
        path: summarizer/.venv
        key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}

    - name: Install dependencies
      if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      run: |
        echo "Installing dependencies..."
        cd summarizer
        poetry install --no-interaction


    - name: Run tests
      working-directory: ./summarizer
      env:
        # General settinfgs
        HUGGING_FACE_TOKEN: ${{ secrets.HUGGING_FACE_TOKEN }}
        INFERENCE_DEVICE: cpu
        
        # Azure provider tests
        AI_FOUNDRY_PROJECT_ENDPOINT: ${{ secrets.AI_FOUNDRY_PROJECT_ENDPOINT }}
        AZURE_CHAT_DEPLOYMENT_NAME: ${{ secrets.AZURE_CHAT_DEPLOYMENT_NAME }}
        AZURE_AUDIO_DEPLOYMENT_NAME: ${{ secrets.AZURE_AUDIO_DEPLOYMENT_NAME }}
        
        # Ollama tests
        OLLAMA_HOST: http://localhost:11434
        OLLAMA_MODEL: ${{ env.OLLAMA_MODEL_NAME }}

        # Workflow tests, choose a provider
        CHAT_COMPLETION_PROVIDER: "azure"
        AUDIO_COMPLETION_PROVIDER: "azure"
        SKIP_WORKFLOW_TESTS: ${{ steps.dapr-setup.outputs.dapr-available != 'true' }}

      run: |
        # Ensure daprd is available for workflow tests
        export PATH="$HOME/.dapr/bin:$PATH"
        echo "SKIP_WORKFLOW_TESTS is set to: $SKIP_WORKFLOW_TESTS"
        if [ "$SKIP_WORKFLOW_TESTS" = "true" ]; then
          echo "Workflow tests will be skipped due to Dapr setup issues"
        else
          echo "Workflow tests will be executed"
          if command -v daprd &> /dev/null; then
            echo "daprd found: $(which daprd)"
            daprd --version
          else
            echo "Warning: daprd not found in PATH, workflow tests may fail"
          fi
        fi
        poetry run pytest tests/ -v --tb=short

    - name: Cleanup Dapr services
      if: always()
      run: |
        # Stop placement and scheduler services
        if [ -f /tmp/placement.pid ]; then
          kill $(cat /tmp/placement.pid) 2>/dev/null || true
          rm -f /tmp/placement.pid
        fi
        
        if [ -f /tmp/scheduler.pid ]; then
          kill $(cat /tmp/scheduler.pid) 2>/dev/null || true
          rm -f /tmp/scheduler.pid
        fi
        
        # Stop Ollama service
        pkill -f "ollama serve" 2>/dev/null || true
        
        echo "Dapr and Ollama services cleanup completed"